version: "2.1"

services:
  revproxy:
    image: acqueon/aiq-revproxy:1.1
    container_name: revproxy
    user: '123:nginx'
    ports:
      - '80:8080'
      - '443:8443'
    restart: always
    read_only: true
    pids_limit: 50
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - //opt/aiq-reports/core:/opt/aiq-reports/core
      - /opt/aiq-reports/core/var/cache:/var/cache/nginx
      - /opt/aiq-reports/core/var/log/nginx:/var/log/nginx
      - /opt/aiq-reports/core/var/run/nginx:/var/run/nginx
      - /opt/aiq-reports/revproxy/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - /opt/aiq-reports/revproxy/nginx/default.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_WORKER_PROCESSES=1028
    env_file:
      - /opt/aiq-reports/core/envfile.core
    networks:
      - aiq

networks:
    aiq:
      external: true
